// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package userRepo

import (
	"time"

	"github.com/google/uuid"
)

type Event struct {
	ID               uuid.UUID
	EventName        string
	EventDate        time.Time
	EventLocation    string
	EventDescription string
	EventImageUrl    string
	OrganizationFk   uuid.UUID
}

type Invite struct {
	ID             uuid.UUID
	ExpirationDate time.Time
	Capacity       int32
	OrgUserFk      int32
	EntityUuid     uuid.UUID
	EntityType     int32
}

type OrgUser struct {
	ID             int32
	PoliciesNum    int32
	UserFk         uuid.UUID
	OrganizationFk uuid.UUID
}

type Organization struct {
	ID          uuid.UUID
	OrgName     string
	City        string
	OrgImageUrl string
}

type User struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	PhoneNumber  string
	FirstName    string
	LastName     string
	Username     string
	ImageUrl     string
	Validated    bool
}

type UserEvent struct {
	ID               int32
	UserFk           uuid.UUID
	EventFk          uuid.UUID
	ApplicationState string
}
