package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// User represents a row from 'public.Users'.
type User struct {
	UserID   int            `json:"UserID"`   // UserID
	UserUUID sql.NullString `json:"UserUuid"` // UserUuid
	// xo fields
	_exists, _deleted bool
}

// Exists returns true when the User exists in the database.
func (u *User) Exists() bool {
	return u._exists
}

// Deleted returns true when the User has been marked for deletion from
// the database.
func (u *User) Deleted() bool {
	return u._deleted
}

// Insert inserts the User to the database.
func (u *User) Insert(ctx context.Context, db DB) error {
	switch {
	case u._exists: // already exists
		return logerror(&ErrInsertFailed{ErrAlreadyExists})
	case u._deleted: // deleted
		return logerror(&ErrInsertFailed{ErrMarkedForDeletion})
	}
	// insert (primary key generated and returned by database)
	const sqlstr = `INSERT INTO public.Users (` +
		`UserUuid` +
		`) VALUES (` +
		`$1` +
		`) RETURNING UserID`
	// run
	logf(sqlstr, u.UserUUID)
	if err := db.QueryRowContext(ctx, sqlstr, u.UserUUID).Scan(&u.UserID); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Update updates a User in the database.
func (u *User) Update(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return logerror(&ErrUpdateFailed{ErrDoesNotExist})
	case u._deleted: // deleted
		return logerror(&ErrUpdateFailed{ErrMarkedForDeletion})
	}
	// update with composite primary key
	const sqlstr = `UPDATE public.Users SET ` +
		`UserUuid = $1 ` +
		`WHERE UserID = $2`
	// run
	logf(sqlstr, u.UserUUID, u.UserID)
	if _, err := db.ExecContext(ctx, sqlstr, u.UserUUID, u.UserID); err != nil {
		return logerror(err)
	}
	return nil
}

// Save saves the User to the database.
func (u *User) Save(ctx context.Context, db DB) error {
	if u.Exists() {
		return u.Update(ctx, db)
	}
	return u.Insert(ctx, db)
}

// Upsert performs an upsert for User.
func (u *User) Upsert(ctx context.Context, db DB) error {
	switch {
	case u._deleted: // deleted
		return logerror(&ErrUpsertFailed{ErrMarkedForDeletion})
	}
	// upsert
	const sqlstr = `INSERT INTO public.Users (` +
		`UserID, UserUuid` +
		`) VALUES (` +
		`$1, $2` +
		`)` +
		` ON CONFLICT (UserID) DO ` +
		`UPDATE SET ` +
		`UserUuid = EXCLUDED.UserUuid `
	// run
	logf(sqlstr, u.UserID, u.UserUUID)
	if _, err := db.ExecContext(ctx, sqlstr, u.UserID, u.UserUUID); err != nil {
		return logerror(err)
	}
	// set exists
	u._exists = true
	return nil
}

// Delete deletes the User from the database.
func (u *User) Delete(ctx context.Context, db DB) error {
	switch {
	case !u._exists: // doesn't exist
		return nil
	case u._deleted: // deleted
		return nil
	}
	// delete with single primary key
	const sqlstr = `DELETE FROM public.Users ` +
		`WHERE UserID = $1`
	// run
	logf(sqlstr, u.UserID)
	if _, err := db.ExecContext(ctx, sqlstr, u.UserID); err != nil {
		return logerror(err)
	}
	// set deleted
	u._deleted = true
	return nil
}

// UserByUserUUID retrieves a row from 'public.Users' as a User.
//
// Generated from index 'UserUuidIndex'.
func UserByUserUUID(ctx context.Context, db DB, userUUID sql.NullString) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`UserID, UserUuid ` +
		`FROM public.Users ` +
		`WHERE UserUuid = $1`
	// run
	logf(sqlstr, userUUID)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, userUUID).Scan(&u.UserID, &u.UserUUID); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}

// UserByUserID retrieves a row from 'public.Users' as a User.
//
// Generated from index 'Users_pkey'.
func UserByUserID(ctx context.Context, db DB, userID int) (*User, error) {
	// query
	const sqlstr = `SELECT ` +
		`UserID, UserUuid ` +
		`FROM public.Users ` +
		`WHERE UserID = $1`
	// run
	logf(sqlstr, userID)
	u := User{
		_exists: true,
	}
	if err := db.QueryRowContext(ctx, sqlstr, userID).Scan(&u.UserID, &u.UserUUID); err != nil {
		return nil, logerror(err)
	}
	return &u, nil
}
