basePath: /
definitions:
  dto.ReqEvent:
    properties:
      eventDate:
        type: string
      eventDescription:
        type: string
      eventLocation:
        type: string
      eventName:
        type: string
    type: object
  dto.UserSignIn:
    properties:
      email:
        type: string
      password:
        type: string
    type: object
  dto.UserSignUp:
    properties:
      email:
        type: string
      first_name:
        type: string
      image_url:
        type: string
      last_name:
        type: string
      password:
        type: string
      phone_number:
        type: string
      user_name:
        type: string
    type: object
info:
  contact: {}
  description: The api docs
  title: Gamma User Api
  version: "0.0"
paths:
  /api/event/{org_uuid}:
    get:
      consumes:
      - application/json
      description: Get events for a particular organization
      parameters:
      - description: Bearer <your_token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Org uuid
        in: path
        name: org_uuid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Org Events
    post:
      consumes:
      - application/json
      description: Create an event for a particular org
      parameters:
      - description: Bearer <your_token>
        in: header
        name: Authorization
        required: true
        type: string
      - description: Org uuid
        in: path
        name: org_uuid
        required: true
        type: string
      - description: Also needs 'event_image' which is a file
        in: body
        name: event_data
        required: true
        schema:
          $ref: '#/definitions/dto.ReqEvent'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Create Event
  /api/events:
    get:
      consumes:
      - application/json
      description: Get a list of events going on
      parameters:
      - description: Bearer <your_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Events
  /api/orgs:
    get:
      consumes:
      - application/json
      description: Get the organizations you are in
      parameters:
      - description: Bearer <your_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Self Orgs
  /api/user:
    get:
      consumes:
      - application/json
      description: Get data about self and events
      parameters:
      - description: Bearer <your_token>
        in: header
        name: Authorization
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Self
  /auth/refresh:
    get:
      consumes:
      - application/json
      description: Send in a valid refresh token (http only cookie) and get a new
        set of tokens
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Refresh Tokens
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Sign In User
      parameters:
      - description: Username and Password
        in: body
        name: Details
        required: true
        schema:
          $ref: '#/definitions/dto.UserSignIn'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Sign In
  /auth/signup:
    post:
      consumes:
      - application/json
      description: Sign Up User
      parameters:
      - description: Data required to create an account
        in: body
        name: Details
        required: true
        schema:
          $ref: '#/definitions/dto.UserSignUp'
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Sign Up
swagger: "2.0"
